;ASM notation source
XXX	equ $FF	;empty note value
MUSIC_data
;Track $00
MUSIC_track00
	dta $28,XXX,$23,XXX,$28,XXX,$35,XXX,XXX,XXX,$2F,XXX,$3C,XXX,XXX,XXX
	dta $51,XXX,$48,XXX,$51,XXX,$6C,XXX,XXX,XXX,$60,XXX,$79,XXX,XXX,XXX
	dta $A2,XXX,$90,XXX,$A2,XXX,$D9,XXX,XXX,XXX,$CC,XXX,$D9,XXX,$E6,XXX
	dta $F3,XXX,XXX,XXX,XXX,XXX,XXX,$F3,$C1,$79,XXX,XXX,XXX,XXX,XXX,XXX
