//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Rmt.rc
//
#define IDDEFAULT                       3
#define IDOK2                           3
#define IDTESTNOW                       3
#define IDTRY                           4
#define IDRESET                         4
#define IDRESTORE                       5
#define IDPLAYSTOP                      6
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_RMTTYPE                     129
#define IDB_GFX                         130
#define IDD_FILENEW                     131
#define IDR_TOOLBARPLAY                 133
#define IDD_EXPSAP                      135
#define IDD_EXPORT_STRIPPED_RMT         136
#define IDD_EXPMSX                      137
#define IDR_TOOLBARBLOCK                138
#define IDR_TOOLBARCHANNELS             140
#define IDC_CURSORCHANNELONOFF          142
#define IDC_CURSORENVVOLUME             144
#define IDD_CONFIG                      145
#define IDC_CURSORGOTO                  145
#define IDD_EFFECTS                     146
#define IDC_CURSORDLG                   146
#define IDD_IMPORTMOD                   147
#define IDD_IMPORTMODFINISHED           148
#define IDC_CURSORCHANNELONOFF1         148
#define IDI_ICONEXCLAMATION             149
#define IDC_CURSORSETPOS                149
#define IDD_SONGTRACKSORDER             150
#define IDD_INSTRCHANGE                 151
#define IDD_IMPORTTMC                   152
#define IDD_IMPORTTMCFINISHED           153
#define IDD_RENUMBERTRACKS              154
#define IDD_RENUMBERINSTRUMENTS         155
#define IDD_SONGINSERTCOPYORCLONEOFSONGLINES 156
#define IDD_TRACKSLOAD                  157
#define IDD_EXPORT_ASM                  158
#define IDD_OCTAVESELECT                160
#define IDD_INSTRUMENTSELECT            161
#define IDD_VOLUMESELECT                162
#define IDD_CONFIG2                     162
#define IDD_PATHS                       163
#define IDD_FILEPATHDLG                 164
#define IDD_CHANNELSSELECT              165
#define IDD_CHANGEMAXTRACKLEN           166
#define IDD_TUNING                      167
#define IDD_EXPORT_RMTPLAYER_ASM        168
#define IDC_MAXTRACKLEN                 1002
#define IDC_COMBOTYPE                   1003
#define IDC_RMTVERSION                  1004
#define IDC_RMTAUTHOR                   1005
#define IDC_NAME                        1006
#define IDC_AUTHOR                      1007
#define IDC_DATE                        1008
#define IDC_SUBSONGS                    1009
#define IDC_ADDR                        1010
#define IDC_INFO                        1011
#define IDC_RASTERLINE                  1017
#define IDC_EDIT                        1018
#define IDC_MSXSHUFFLE                  1019
#define IDC_PREV                        1020
#define IDC_MSXREGIONAUTO               1021
#define IDC_ABOUTPOKEY                  1023
#define IDC_ABOUT6502                   1025
#define IDC_RMTFEAT                     1025
#define IDC_CREDITS                     1026
#define IDC_COPYTOCLIPBOARD             1026
#define IDC_MIDI_DEVICE                 1027
#define IDC_MIDI_TR                     1028
#define IDC_TRACKLINEPRIMARYHIGHLIGHT   1029
#define IDC_TRACKLINESECONDARYHIGHLIGHT 1030
#define IDC_MIDI_VOLUMEOFFSET           1031
#define IDC_EFF_COMBO                   1033
#define IDC_SCALINGPERCENTAGE           1033
#define IDC_KEYBOARD_ESCRESETATARISOUND 1034
#define IDC_KEYBOARD_ASKWHENCONTROL_S   1035
#define IDC_TRACKLINEPRIMARYHIGHLIGHT2  1036
#define IDC_EFF_EDIT1                   1037
#define IDC_NTSC                        1038
#define IDC_EFF_EDIT2                   1038
#define IDC_EFF_EDIT3                   1039
#define IDC_SMOOTH_SCROLL               1039
#define IDC_EFF_P1                      1040
#define IDC_DEBUGDISPLAY                1040
#define IDC_EFF_P2                      1041
#define IDC_MIDI_NOTEOFF                1041
#define IDC_EFF_P3                      1042
#define IDC_TRACKERDRIVERVERSION        1043
#define IDC_RADIO1                      1045
#define IDC_RADIO2                      1046
#define IDC_CHECK1                      1047
#define IDC_RADIO3                      1047
#define IDC_CHECK2                      1048
#define IDC_RADIO4                      1048
#define IDC_CHECK3                      1049
#define IDC_RADIO5                      1049
#define IDC_CHECK4                      1050
#define IDC_RADIO6                      1050
#define IDC_L1                          1051
#define IDC_RADIO7                      1051
#define IDC_CHECKONEINSTRUMENT          1051
#define IDC_CHECK10                     1051
#define IDC_L2                          1052
#define IDC_CHECK9                      1052
#define IDC_CHECK11                     1052
#define IDC_L3                          1053
#define IDC_CHECK12                     1053
#define IDC_L4                          1054
#define IDC_CHECK13                     1054
#define IDC_R1                          1055
#define IDC_R2                          1056
#define IDC_R3                          1057
#define IDC_R4                          1058
#define IDC_L1D                         1059
#define IDC_L2D                         1060
#define IDC_L3D                         1061
#define IDC_L4D                         1062
#define IDC_R1D                         1063
#define IDC_R2D                         1064
#define IDC_R3D                         1065
#define IDC_R4D                         1066
#define IDC_NOTHING                     1067
#define IDC_MONOSTEREO                  1069
#define IDC_DEFAULT                     1070
#define IDC_COMBO1                      1070
#define IDC_STEREOMONO                  1071
#define IDC_COMBO2                      1071
#define IDC_COMBO3                      1072
#define IDC_COMBO4                      1073
#define IDC_COPYLEFTRIGHT               1073
#define IDC_COMBO5                      1074
#define IDC_COPYRIGHTLEFT               1074
#define IDC_COMBO6                      1075
#define IDC_CLEARALL                    1075
#define IDC_COMBO7                      1076
#define IDC_COMBO8                      1077
#define IDC_COMBO9                      1078
#define IDC_BUTTON1                     1079
#define IDC_INSTRUMENT                  1080
#define IDC_TITLE                       1080
#define IDC_CHECK5                      1081
#define IDC_COMBO11                     1081
#define IDC_BUTTON3                     1081
#define IDC_CHECK6                      1082
#define IDC_COMBO12                     1082
#define IDC_CHECK7                      1083
#define IDC_COMBO10                     1083
#define IDC_INFO2                       1084
#define IDC_BUTTON2                     1084
#define IDC_KEYBOARD_UPDOWNCONTINUE     1085
#define IDC_TITLE2                      1085
#define IDC_CHECK8                      1086
#define IDC_KEYBOARD_REMEMBEROCTAVESANDVOLUMES 1086
#define IDC_COLORNUMBER                 1089
#define IDC_SCROLLBAR1                  1091
#define IDC_SONGLINE                    1092
#define IDC_SONGLINEFROM                1092
#define IDC_TUNING                      1093
#define IDC_SONGLINETO                  1094
#define IDC_CLONETRACKS                 1095
#define IDC_VOLUMEP                     1096
#define IDC_TEXT1                       1097
#define IDC_TEXT2                       1098
#define IDC_KEYBOARD_LAYOUT             1104
#define IDC_LABELSPREFIX                1108
#define IDC_OCTAVE1                     1109
#define IDC_OCTAVE2                     1110
#define IDC_LIST1                       1110
#define IDC_OCTAVE3                     1111
#define IDC_OCTAVE4                     1112
#define IDC_NOHWSOUNDBUFFER             1112
#define IDC_OCTAVE5                     1113
#define IDC_SFX                         1113
#define IDC_WARNING                     1114
#define IDC_TRACKLINEALTNUMBERING       1115
#define IDC_PATHS                       1116
#define IDC_EDIT1                       1117
#define IDC_EDIT2                       1118
#define IDC_DIRLIST                     1118
#define IDC_EDIT3                       1119
#define IDC_DRIVELIST                   1119
#define IDC_CURSORMAXLATITUDE           1120
#define IDC_DISPLAYFLATNOTES            1120
#define IDC_GLOBALVOLUMEFADE            1121
#define IDC_NOSTARTINGSONGLINE          1122
#define IDC_SPEEDINFO                   1122
#define IDC_USEGERMANNOTATION           1123
#define IDC_DRIVERVERSION               1123
#define IDC_BASETUNING                  1124
#define IDC_UNISON_L                    1127
#define IDC_MINOR_2ND_L                 1128
#define IDC_MAJOR_2ND_L                 1129
#define IDC_MINOR_3RD_L                 1130
#define IDC_MAJOR_3RD_L                 1131
#define IDC_PERFECT_4TH_L               1132
#define IDC_TRITONE_L                   1133
#define IDC_PERFECT_5TH_L               1134
#define IDC_MINOR_6TH_L                 1135
#define IDC_MAJOR_6TH_L                 1136
#define IDC_MINOR_7TH_L                 1137
#define IDC_MAJOR_7TH_L                 1138
#define IDC_UNISON_R                    1139
#define IDC_MINOR_2ND_R                 1140
#define IDC_MAJOR_2ND_R                 1141
#define IDC_MINOR_3RD_R                 1142
#define IDC_MAJOR_3RD_R                 1143
#define IDC_PERFECT_4TH_R               1144
#define IDC_TRITONE_R                   1145
#define IDC_PERFECT_5TH_R               1146
#define IDC_MINOR_6TH_R                 1147
#define IDC_MAJOR_6TH_R                 1148
#define IDC_MINOR_7TH_R                 1149
#define IDC_MAJOR_7TH_R                 1150
#define IDC_BASENOTE                    1151
#define IDC_TEMPERAMENT                 1152
#define IDC_RMT_BASE_ADDR               1152
#define IDC_OCTAVE_L                    1153
#define IDC_RMT_MODULE_ASM_LABEL        1153
#define IDC_OCTAVE_R                    1154
#define IDC_RASM_SFX                    1154
#define IDC_CHK_RELOCATE_TRACKS         1155
#define IDC_CHK_RELOCATE_TRACKS2        1156
#define IDC_CHK_RELOCATE_SONG           1156
#define IDC_EDIT_TRACKS_LABEL           1157
#define IDC_EDIT_SONG_LINES_LABEL       1158
#define IDC_CHK_RELOCATE_INSTRUMENTS    1159
#define IDC_EDIT_INSTRUMENTS_LABEL      1160
#define IDC_COMBO_ASM_FORMAT            1161
#define IDC_COMBO_LINESAFTER            9999
#define ID_INSTR_SAVE                   32771
#define ID_INSTR_LOAD                   32772
#define ID_FILE_EXPORT_AS               32773
#define ID_TRACK_COPY                   32774
#define ID_TRACK_PASTE                  32775
#define ID_TRACK_CUT                    32776
#define ID_INSTR_COPY                   32777
#define ID_INSTR_PASTE                  32778
#define ID_INSTR_CUT                    32779
#define ID_TRACK_DELETE                 32780
#define ID_INSTR_DELETE                 32781
#define ID_SONG_COPYLINE                32782
#define ID_SONG_PASTELINE               32783
#define ID_SONG_CLEARLINE               32784
#define ID_BUTTON32785                  32785
#define ID_BUTTON32786                  32786
#define ID_BUTTON32787                  32787
#define ID_BUTTON32788                  32788
#define ID_BUTTPLAY1                    32789
#define ID_BUTTON32790					32790
#define ID_BUTTON32791					32791
#define ID_BUTTON32792					32792
#define ID_PLAY_FOLLOW					32794
#define ID_PLAY_BOOKMARK                32795
#define ID_PLAY_START					32796
#define ID_PLAY_FROM					32797
#define ID_PLAY_PATTERN					32798
#define ID_PLAY_STOP					32799
#define ID_EDIT_TRACKS                  32800
#define ID_BUTTON32801                  32801
#define ID_EDIT_INSTRUMENTS             32802
#define ID_BUTTON32803                  32803
#define ID_EDIT_SONG                    32804
#define ID_EDIT_INFO                    32805
#define ID_EM_TRACKS                    32806
#define ID_EM_INSTRUMENTS               32807
#define ID_EM_INFO                      32808
#define ID_EM_SONG                      32809
#define ID_PROVEMODE                    32810
#define ID_VIEW_VOLUMEANALYZER          32811
#define ID_VIEW_INSTRUMENTACTIVEHELP    32812
#define ID_VIEW_BLOCKTOOLBAR            32813
#define ID_BLOCK_NOTEUP                 32814
#define ID_BLOCK_NOTEDOWN               32815
#define ID_BLOCK_VOLUMEUP               32816
#define ID_BLOCK_VOLUMEDOWN             32817
#define ID_BLOCK_INSTRLEFT              32818
#define ID_BLOCK_INSTRRIGHT             32819
#define ID_BLOCK_PLAY                   32820
#define ID_BLOCK_INSTRALL               32821
#define ID_BLOCK_BACKUP                 32822
#define ID_CHAN1                        32823
#define ID_CHAN2                        32824
#define ID_CHAN3                        32825
#define ID_CHAN4                        32826
#define ID_CHAN5                        32833
#define ID_CHAN6                        32834
#define ID_CHAN7                        32835
#define ID_CHAN8                        32836
#define ID_VIEW_POKEYREGS               32837
#define ID_MIDIONOFF                    32838
#define ID_VIEW_CONFIGURATION           32841
#define ID_BLOCK_COPY                   32842
#define ID_BLOCK_PASTE                  32843
#define ID_BLOCK_DELETE                 32844
#define ID_BLOCK_CUT                    32845
#define ID_BLOCK_SELECTALL              32847
#define ID_BLOCK_EXCHANGE               32848
#define ID_BLOCK_EFFECT                 32849
#define ID_TRACK_ALLTRACKSCLEANUP       32850
#define ID_INSTR_ALLINSTRUMENTSCLEANUP  32851
#define ID_SONG_INSERTNEWEMPTYLINE      32852
#define ID_SONG_DELETEACTUALLINE        32853
#define ID_SONG_PREPARENEWLINEWITHUNUSEDTRACKS 32854
#define ID_SONG_INSERTNEWLINEWITHUNUSEDTRACKS 32854
#define ID_SONG_INSERTCOPYORCLONEOFSONGLINES 32855
#define ID_FILE_IMPORT                  32856
#define ID_SONG_TRACKSORDERCHANGEMONOSTEREO 32857
#define ID_SONG_TRACKSORDERCHANGE       32857
#define ID_SONG_SONGSWITCH4_8           32859
#define ID_INSTRUMENT_INFO              32860
#define ID_INSTRUMENT_CHANGE            32862
#define ID_TRACK_SEARCHANDBUILDLOOP     32863
#define ID_SONG_SEARCHANDBUILDLOOPSINALLTRACKS 32864
#define ID_TRACK_EXPANDLOOP             32865
#define ID_SONG_EXPANDLOOPSINALLTRACKS  32866
#define ID_SONG_SIZEOPTIMIZATION        32867
#define ID_VIEW_PLAYTIMECOUNTER         32868
#define ID_INSTRUMENT_CLEARALLUNUSEDINSTRUMENTS 32869
#define ID_TRACK_CLEARALLTRACKSUNUSEDINSONG 32870
#define ID_TRACK_INFOABOUTUSINGOFACTUALTRACK 32871
#define ID_TRACK_RENUMBERALLTRACKS      32873
#define ID_INSTRUMENT_RENUMBERALLINSTRUMENTS 32874
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMELRENVELOPESONLY 32875
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMELENVELOPEONLY 32876
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMERENVELOPEONLY 32877
#define ID_INSTRUMENT_PASTESPECIAL_ENVELOPEPARAMETERSONLY 32878
#define ID_INSTRUMENT_PASTESPECIAL_TABLEONLY 32879
#define ID_BLOCK_PASTESPECIAL_VOLUMEVALUESONLY 32880
#define ID_BLOCK_PASTESPECIAL_SPEEDVALUESONLY 32881
#define ID_BLOCK_PASTESPECIAL_MERGEWITHCURRENTCONTENT 32882
#define ID_SONG_PUTNEWEMPTYUNUSEDTRACK  32887
#define ID_TRACK_LOAD                   32888
#define ID_TRACK_SAVE                   32889
#define ID_TRACK_CLEARALLDUPLICATEDTRACKS 32890
#define ID_BUTTONCOMBO1                 32891
#define ID_SONG_MAKETRACKSDUPLICATE     32892
#define ID_FILE_RELOAD                  32895
#define ID_UNDO_UNDO                    32896
#define ID_UNDO_REDO                    32897
#define ID_UNDO_CLEARUNDOREDO           32898
#define ID_WANTEXIT                     32899
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMERTOLENVELOPEONLY 32900
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMELTORENVELOPEONLY 32901
#define ID_INSTRUMENT_PASTESPECIAL_VOLUMEENVANDENVELOPEPARSONLY 32902
#define ID_INSTRUMENT_PASTESPECIAL_INSERTVOLUMEENVSANDENVELOPEPARSTOCURSORPOSITION 32903
#define ID_TRACK_CURSORGOTOTHESPEEDCOLUMN 32904
#define ID_SONG_SONGCHANGEMAXIMALLENGTHOFTRACKS 32905
#define ID_Menu                         32906
#define ID_VIEW_TUNING                  32907
#define IDS_RMTVERSION                  61446
#define IDS_RMTAUTHOR                   61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32908
#define _APS_NEXT_CONTROL_VALUE         1162
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
